inherit_gem:
  rubocop-rails_config:
    - config/rails.yml

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/ClassAndModuleChildren:
  EnforcedStyle: nested

Lint/Debugger:
  Enabled: true