default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV["WEB_CONCURRENCY"] * 5 %>

development:
  <<: *default
  database: development
  host: <%= Rails.root.join('tmp', 'database', 'pgsocket') %>
  username: postgres
  password: postgres

test:
  <<: *default
  database: test
  username: postgres
  password: postgres

production:
  <<: *default
  pool: <%= (Sidekiq.server? ? ENV['SIDEKIQ_CONCURRENCY'] : ENV['WEB_CONCURRENCY']).to_i * 5  %>
  url: <%= ENV['DATABASE_URL'] %>